### ISSUE TITLE
Prasyarat tidak lengkap.

### ISSUE THREAD

**Issue by afiqzx** [Thaza-Kun/samudra#1]
Berikut adalah cara pemasangan yang kini ada di `Readme`.

```
Pemasangan

    - Python 3.8 atau lebih
    - Guna [poetry](https://python-poetry.org/docs/) (digalakkan)
    - poetry install
```

Saya telah mengikut cara pemasangan berikut dan menerima ralat berikut.
```
Traceback (most recent call last):
  File "/home/afiq/Documents/git_clone/samudra/samudra/serve.py", line 3, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'
```

Adakah cara pemasangan tidak lengkap, atau saya tersilap langkah?

Saya juga tertanya jika saya perlu pasang Mysql ke sistem saya terlebih dahulu, kerana ianya tidak dinyatakan di `Readme`.....

**Comment by Thaza-Kun** [comment]
1. Seharusnya, kalau guna dipasang guna `poetry install`, pakej `uvicorn` sudah ada dalam senarai. Poetry tak seharusnya mengabaikan pakej uvicorn kerana berikut merupakan senarai dari `pyproject.toml` 
https://github.com/Thaza-Kun/samudra/blob/master/pyproject.toml
```toml
[tool.poetry]
name = "samudra"
version = "0.4.0"
description = ""
authors = ["Thaza_Kun <61819672+Thaza-Kun@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
peewee = "^3.15.0"
pytomlpp = "^1.0.11"
fastapi = "^0.79.0"
uvicorn = "^0.18.2"
pydantic = "^1.9.1"
pandas = "^1.4.3"
openpyxl = "^3.0.10"
python-dotenv = "^0.20.0"
psycopg2 = {version = "^2.9.3", optional = true, extras = ["cockroach_db"]}
cryptography = {version = "^37.0.4", optional = true, extras = ["cockroach_db", "mysql"]}
PyMySQL = {version = "^1.0.2", optional = true, extras = ["mysql"]}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

2. Jika mahu sambungkannya ke pangkalan MySQL, boleh pasang pakej2 tambahan menggunakan
```shell
poetry install --extras mysql
```
atau `poetry install --extras cockroach_db` jika menggunakan khidmat [CockcroachDB](https://www.cockroachlabs.com/product/)

Samudra menggunakan SQLite untuk kegunaan perseorangan dalam laptop sendiri tetapi mewujudkan pilihan menggunakan pangkalan data berkongsi (seperti MySQL) untuk kegunaan kolaboratif.
